server:
  port: 38080
spring:
  application:
    name: im-netty-server
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 400
        max-active: 600
        max-wait: 1000
    timeout: 10000
    database: 0
    
#eureka:
#  instance:
#    hostname: 127.0.0.1
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 10
#  client:
#    enabled: true
#    service-url: 
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

