server:
  port: 38082
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im_kpanther?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  resources:
    add-mappings: true

  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 400
        max-active: 600
        max-wait: 1000
    timeout: 10000
    database: 0